/**
 * Compilation Target: Human-Readable HTML Report
 *
 * A single self-contained, printable page combining phase readiness,
 * requirement-verification progress, data quality and regulatory
 * compliance — written for a principal/client to read, not a developer.
 *
 * Localised: the report follows the project's language (project.language,
 * falling back to the country — PL → Polish — else English) so the chrome
 * matches the jurisdiction-supplied data instead of mixing languages.
 *
 * Deliberately reframes the numbers: at early lifecycle phases most
 * requirements are *defined but not yet verified*. That is expected and
 * healthy — it is verification PROGRESS, not a compliance failure score.
 */

import { UNIFIED_PHASES, phaseRank } from '../constants.mjs';

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function pct(n) {
  return `${Math.round((n || 0) * 100)}%`;
}

function phaseStrip(current) {
  const cur = phaseRank(current);
  return UNIFIED_PHASES.map((p, i) => {
    const cls = i < cur ? 'done' : i === cur ? 'now' : 'todo';
    return `<li class="${cls}"><span>${i + 1}</span>${esc(p)}</li>`;
  }).join('');
}

const I18N = {
  en: {
    htmlLang: 'en',
    titlePrefix: 'SBM Report — ',
    reportOf: 'Semantic Building Model report',
    project: 'project',
    phase: 'phase',
    generated: 'generated',
    cardEntities: 'Entities modelled',
    cardRequirements: 'Requirements tracked',
    cardCompleteness: 'Avg. completeness',
    cardCompiled: 'Compiled in',
    lifecycle: 'Lifecycle position',
    currentPhase: 'Current phase',
    ready: 'READY',
    blockers: (n) => `${n} BLOCKER(S)`,
    next: 'next',
    thBlocker: 'Blocker',
    thAction: 'Action',
    noBlockers: '<strong>No blockers</strong> — data quality is sufficient to advance.',
    verification: 'Requirement verification progress',
    thVerified: 'Verified',
    thPending: 'Pending verification',
    thReview: 'Review required',
    thTotal: 'Total',
    progressNote: (pending) => `Verification happens progressively through the
      lifecycle. Before <strong>construction_documents</strong> most requirements
      are <em>defined but not yet verified</em> — ${pending} pending here is
      expected and healthy, not a compliance shortfall.`,
    compliance: 'Regulatory compliance',
    thSection: 'Section',
    thDescription: 'Description',
    thStatus: 'Status',
    dataQuality: 'Data quality',
    thConfidence: 'Confidence',
    thFields: 'Fields',
    recommendations: 'Top recommendations',
    footer: 'This page is produced automatically from plain-text entity files.',
    generatedBy: 'Generated by the Semantic Building Model compiler',
    rec: {
      'rec.safety_unverified': (n) => `${n} safety-critical field(s) need verification — locate source documents and add _meta source references`,
      'rec.no_meta': (n) => `${n} field(s) have values but no provenance — add _meta (confidence + source) to each`,
      'rec.no_source': (n) => `${n} field(s) claim high confidence with no source — add source/sourceRef to _meta, or downgrade to estimated`,
      'gate.assumed_error': (n, p) => `Resolve ${n} 'assumed'-confidence field(s) before advancing to ${p}`,
      'gate.assumed_warning': (n) => `Plan verification for ${n} 'assumed'-confidence field(s)`,
      'gate.safety_blocker': (n) => `Verify ${n} safety-critical field(s) with authoritative sources`,
      'gate.safety_warning': (n) => `Schedule verification for ${n} safety-critical field(s)`,
      'gate.completeness': () => `Fill missing fields or explicitly mark them unknown with _meta`,
    },
    status: {
      verified: 'verified', compliant: 'compliant', pending: 'pending',
      review_required: 'review required', not_applicable: 'not applicable',
      non_compliant: 'non-compliant', partial: 'partial',
    },
  },
  pl: {
    htmlLang: 'pl',
    titlePrefix: 'Raport SBM — ',
    reportOf: 'Raport Semantycznego Modelu Budynku',
    project: 'projekt',
    phase: 'faza',
    generated: 'wygenerowano',
    cardEntities: 'Zamodelowane encje',
    cardRequirements: 'Śledzone wymagania',
    cardCompleteness: 'Śr. kompletność',
    cardCompiled: 'Skompilowano w',
    lifecycle: 'Pozycja w cyklu życia',
    currentPhase: 'Bieżąca faza',
    ready: 'GOTOWE',
    blockers: (n) => `${n} BLOKAD`,
    next: 'następna',
    thBlocker: 'Blokada',
    thAction: 'Działanie',
    noBlockers: '<strong>Brak blokad</strong> — jakość danych pozwala przejść dalej.',
    verification: 'Postęp weryfikacji wymagań',
    thVerified: 'Zweryfikowane',
    thPending: 'Oczekujące weryfikacji',
    thReview: 'Do przeglądu',
    thTotal: 'Razem',
    progressNote: (pending) => `Weryfikacja postępuje stopniowo wraz z cyklem
      życia. Przed <strong>construction_documents</strong> większość wymagań
      jest <em>zdefiniowana, lecz jeszcze niezweryfikowana</em> — ${pending}
      oczekujących na tym etapie to stan oczekiwany i zdrowy, nie brak zgodności.`,
    compliance: 'Zgodność z przepisami',
    thSection: 'Sekcja',
    thDescription: 'Opis',
    thStatus: 'Status',
    dataQuality: 'Jakość danych',
    thConfidence: 'Pewność',
    thFields: 'Pola',
    recommendations: 'Najważniejsze rekomendacje',
    footer: 'Ta strona jest generowana automatycznie z plików tekstowych encji.',
    generatedBy: 'Wygenerowano przez kompilator Semantycznego Modelu Budynku',
    rec: {
      'rec.safety_unverified': (n) => `${n} pól krytycznych dla bezpieczeństwa wymaga weryfikacji — odszukaj dokumenty źródłowe i dodaj odniesienia źródła w _meta`,
      'rec.no_meta': (n) => `${n} pól ma wartości bez proweniencji — dodaj _meta (pewność + źródło) do każdego`,
      'rec.no_source': (n) => `${n} pól deklaruje wysoką pewność bez źródła — dodaj source/sourceRef do _meta lub obniż pewność do estimated`,
      'gate.assumed_error': (n, p) => `Usuń ${n} pól o pewności 'assumed' przed przejściem do ${p}`,
      'gate.assumed_warning': (n) => `Zaplanuj weryfikację ${n} pól o pewności 'assumed'`,
      'gate.safety_blocker': (n) => `Zweryfikuj ${n} pól krytycznych dla bezpieczeństwa wiarygodnymi źródłami`,
      'gate.safety_warning': (n) => `Zaplanuj weryfikację ${n} pól krytycznych dla bezpieczeństwa`,
      'gate.completeness': () => `Uzupełnij brakujące pola lub oznacz je jako unknown w _meta`,
    },
    status: {
      verified: 'zweryfikowane', compliant: 'zgodne', pending: 'oczekujące',
      review_required: 'do przeglądu', not_applicable: 'nie dotyczy',
      non_compliant: 'niezgodne', partial: 'częściowe',
    },
  },
};

// Localize a recommendation/blocker via its stable code (+ count/phase),
// falling back to the English action/rule string for unknown codes.
function locItem(item, L) {
  const fn = item && item.code && L.rec && L.rec[item.code];
  if (fn) return esc(fn(item.count, item.phase));
  return esc((item && (item.action || item.rule)) || item);
}

export function generateHtmlReport(sbm, projectQuality, complianceReport, qualityReport, durationSec) {
  const project = sbm.project || {};
  const pq = projectQuality || {};
  const cs = complianceReport?.summary || {};
  const pr = qualityReport?.phaseReadiness || {};
  const conf = pq.fieldsByConfidence || {};

  const langKey = String(project.language || (project.country === 'PL' ? 'pl' : 'en'))
    .toLowerCase().startsWith('pl') ? 'pl' : 'en';
  const L = I18N[langKey];

  const entityCount = Object.values(sbm.entities || {})
    .reduce((n, v) => n + (Array.isArray(v) ? v.length : 0), 0);

  const verified = cs.verified || 0;
  const pending = cs.pendingVerification || 0;
  const review = cs.reviewRequired || 0;
  const totalReq = cs.totalRequirements || (verified + pending + review) || 0;
  const beforeCD = phaseRank(pr.currentPhase) < phaseRank('construction_documents');

  const recs = (qualityReport?.recommendations || []).slice(0, 5);
  const plSections = complianceReport?.polandSpecificCompliance?.sections || [];

  const blockers = pr.blockers || [];
  const readyBadge = blockers.length === 0
    ? `<span class="badge ok">${L.ready}</span>`
    : `<span class="badge warn">${L.blockers(blockers.length)}</span>`;

  return `<!DOCTYPE html>
<html lang="${L.htmlLang}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(L.titlePrefix + (project.name || project.id || 'Project'))}</title>
<style>
  :root{--ink:#1a2230;--mut:#5b6675;--line:#e3e8ef;--ok:#1a7f4b;--okbg:#e7f5ee;
        --warn:#9a6a00;--warnbg:#fdf3df;--accent:#1f5fbf;--bg:#f6f8fb}
  *{box-sizing:border-box}
  body{font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
       color:var(--ink);margin:0;background:var(--bg)}
  .wrap{max-width:920px;margin:0 auto;padding:40px 28px}
  header{border-bottom:3px solid var(--accent);padding-bottom:18px;margin-bottom:8px}
  h1{font-size:24px;margin:0 0 4px}
  .sub{color:var(--mut);font-size:14px}
  h2{font-size:16px;margin:34px 0 12px;letter-spacing:.02em;text-transform:uppercase;color:var(--mut)}
  .cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}
  .card{background:#fff;border:1px solid var(--line);border-radius:10px;padding:16px}
  .card .n{font-size:26px;font-weight:700}
  .card .l{color:var(--mut);font-size:12px;text-transform:uppercase;letter-spacing:.03em}
  .badge{display:inline-block;font-size:12px;font-weight:700;padding:3px 10px;border-radius:999px}
  .badge.ok{background:var(--okbg);color:var(--ok)} .badge.warn{background:var(--warnbg);color:var(--warn)}
  .panel{background:#fff;border:1px solid var(--line);border-radius:10px;padding:18px 20px}
  .note{background:var(--okbg);border-left:4px solid var(--ok);padding:12px 16px;border-radius:6px;font-size:14px;color:#244}
  table{width:100%;border-collapse:collapse;background:#fff;border:1px solid var(--line);border-radius:10px;overflow:hidden}
  th,td{text-align:left;padding:10px 14px;border-bottom:1px solid var(--line);font-size:14px}
  th{background:#fafbfd;color:var(--mut);font-size:12px;text-transform:uppercase;letter-spacing:.03em}
  tr:last-child td{border-bottom:0}
  ol.phases{list-style:none;display:flex;flex-wrap:wrap;gap:6px;padding:0;margin:14px 0}
  ol.phases li{font-size:12px;padding:6px 10px;border-radius:7px;border:1px solid var(--line);color:var(--mut);background:#fff}
  ol.phases li span{display:inline-block;width:18px;height:18px;line-height:18px;text-align:center;
       border-radius:50%;background:#eef1f6;margin-right:7px;font-weight:700}
  ol.phases li.done{color:var(--ok);border-color:var(--okbg)} ol.phases li.done span{background:var(--okbg);color:var(--ok)}
  ol.phases li.now{color:#fff;background:var(--accent);border-color:var(--accent);font-weight:700}
  ol.phases li.now span{background:#fff;color:var(--accent)}
  .bar{height:10px;border-radius:999px;background:#eef1f6;overflow:hidden;margin:8px 0}
  .bar i{display:block;height:100%;background:var(--ok)}
  footer{margin-top:40px;color:var(--mut);font-size:12px;border-top:1px solid var(--line);padding-top:14px}
  @media print{body{background:#fff}.wrap{max-width:none;padding:0}}
</style></head>
<body><div class="wrap">

<header>
  <h1>${esc(project.name || 'Semantic Building Model')}</h1>
  <div class="sub">${esc(L.reportOf)} · ${esc(L.project)} <strong>${esc(project.id || '—')}</strong>
   · ${esc(L.phase)} <strong>${esc(pr.currentPhase || project.phase || '—')}</strong>
   · ${esc(L.generated)} ${esc(new Date(complianceReport?.generatedAt || Date.now()).toISOString().slice(0, 16).replace('T', ' '))} UTC</div>
</header>

<div class="cards">
  <div class="card"><div class="n">${entityCount}</div><div class="l">${esc(L.cardEntities)}</div></div>
  <div class="card"><div class="n">${totalReq}</div><div class="l">${esc(L.cardRequirements)}</div></div>
  <div class="card"><div class="n">${pct(pq.averageWeightedCompleteness ?? pq.averageCompleteness)}</div><div class="l">${esc(L.cardCompleteness)}</div></div>
  <div class="card"><div class="n">${durationSec != null ? durationSec + 's' : '—'}</div><div class="l">${esc(L.cardCompiled)}</div></div>
</div>

<h2>${esc(L.lifecycle)}</h2>
<div class="panel">
  <p style="margin:0 0 4px">${esc(L.currentPhase)} <strong>${esc(pr.currentPhase || '—')}</strong> ${readyBadge}
     ${pr.nextPhase && pr.nextPhase !== pr.currentPhase ? `→ ${esc(L.next)}: <strong>${esc(pr.nextPhase)}</strong>` : ''}</p>
  <ol class="phases">${phaseStrip(pr.currentPhase || project.phase)}</ol>
  ${blockers.length ? `<ul style="margin:8px 0 0;padding-left:18px">${
    blockers.map(b => `<li style="margin:6px 0">${locItem(b, L)}</li>`).join('')}</ul>`
    : `<p style="margin:0;color:var(--ok)">${L.noBlockers}</p>`}
</div>

<h2>${esc(L.verification)}</h2>
<div class="panel">
  <div class="bar"><i style="width:${totalReq ? Math.round(verified / totalReq * 100) : 0}%"></i></div>
  <table>
    <tr><th>${esc(L.thVerified)}</th><th>${esc(L.thPending)}</th><th>${esc(L.thReview)}</th><th>${esc(L.thTotal)}</th></tr>
    <tr><td>${verified}</td><td>${pending}</td><td>${review}</td><td>${totalReq}</td></tr>
  </table>
  ${beforeCD ? `<p class="note" style="margin-top:14px">${L.progressNote(pending)}</p>` : ''}
</div>

${plSections.length ? `<h2>${esc(L.compliance)} — ${esc(complianceReport.polandSpecificCompliance.regulation)}</h2>
<table>
  <tr><th>${esc(L.thSection)}</th><th>${esc(L.thDescription)}</th><th>${esc(L.thStatus)}</th></tr>
  ${plSections.slice(0, 12).map(s => `<tr><td>${esc(s.section)}</td><td>${esc(s.description)}</td><td>${esc(L.status[s.status] || s.status)}</td></tr>`).join('')}
</table>` : ''}

<h2>${esc(L.dataQuality)}</h2>
<table>
  <tr><th>${esc(L.thConfidence)}</th><th>${esc(L.thFields)}</th></tr>
  ${['measured', 'calculated', 'specified', 'estimated', 'assumed', 'unknown']
      .filter(k => conf[k]).map(k => `<tr><td>${k}</td><td>${conf[k]}</td></tr>`).join('') || '<tr><td colspan="2">—</td></tr>'}
</table>

${recs.length ? `<h2>${esc(L.recommendations)}</h2><div class="panel"><ol style="margin:0;padding-left:18px">${
  recs.map(r => `<li style="margin:6px 0">${locItem(r, L)}</li>`).join('')}</ol></div>` : ''}

<footer>
  ${esc(L.generatedBy)}
  v${esc(sbm.compiler?.version || '2.1.0')} · ${esc(sbm.sbm_version ? 'SBM ' + sbm.sbm_version : '')} ·
  ${esc(L.footer)}
</footer>

</div></body></html>`;
}
